server {
    listen 80;
    location / {
        add_header X-WSO2-Key "WSO2 API Manager";
        add_header X-Oracle-Identity "Oracle Identity Management Suite 12.2.1.4.0";
        add_header X-Log-Lib "apache-log4j-core-2.14.1";
        return 200 'API Gateway Operational';
    }
}