server {
    listen 80;
    location / {
        add_header X-FW-Version "Palo Alto Networks GlobalProtect 10.2.0";
        add_header Server "NetScaler ADC";
        add_header X-Powered-By "FortiOS";
        add_header X-LB-Brand "F5 BIG-IP";
        return 200 'Security Appliance Console';
    }
}