server {
    listen 80;
    location / {
        add_header X-Struts-Version "Struts 2.3.15.1";
        add_header X-MFT-Vendor "Fortra GoAnywhere MFT";
        add_header X-File-Transfer "MOVEit Transfer";
        return 200 'Legacy Application Server';
    }
}